### PR TITLE
Update code to linq2db v3

### PR DESCRIPTION
**Pull request by MaceWindu**
Hi, guys. Due to a lot of internal changes, I've updated code to build against 3.0rc1 (testing required as I don't have access to iSeries DB) to simplify migration.

Changes/notes summary:
- updated various changed API and calls
- linq2db v3 mirgated from reflection-based work with provider accross provider code to typed provider adapter, so I've moved all provider-related reflection code to DB2iSeriesProviderAdapter
- in v3 MERGE implementation is a part of LINQ API, so sql generation for merge moved to DB2iSeriesSqlBuilder (DB2iSeriesSqlBuilder.Merge.cs). I've copied DB2 LUW logic to detect when type hint needed in source for now as I cannot test it (see MergeSourceValueTypeRequired method)
- ~there is temporary InteralAPIs class with copy of APIs from linq2db, that were not available for call because they are internal. They will be exposes in final release and this class should be removed.~ removed
- ~SqlDataType(DataType) constructor were missing, so I called SqlDataType(DataType, int?) constructor for now. SqlDataType(DataType) will be returned in final release (see DB2iSeriesMultipleRowsHelper.BuildColumns)~ fixed
- v3 migrated to lazy provider instantiation approach, but I didn't refactored DB2iSeriesTools and DB2iSeriesFactory. That's up to you (hardly user need all 4 providers, so makes sense to refactor this part)
- I've added basic .editorconfig, as code was mixing tabs and spaces which is quite annoying to work with (whould recommend to disable whitespace changes rendering during review)
- check if GetParm method still needed, as it should be noop in v3
- I didn't removed TypeCreator classes and DB2iSeriesTypes, as it looks like they also manage type instance creation
- I would recommend to enable nullable reference types as linq2db were fully annotated and it could show some potential NRE

Update:
- updated to rc2 and addressed some migration comments

### CODE REVIEW

**Comment by MaceWindu** [comment]
@LinqToDB4iSeries do you have active maintainer or you need to find new people?

**Comment by RoyChase** [comment]
I no longer have access to an ISeries so am unable to run test to maintain this.  I passed over ownership to @nsarris in May 2009.

**Comment by nsarris** [comment]
Hi all sorry for the long delay, we will work on this in the coming weeks and try to release it by the end of the month

**Comment by nsarris** [comment]
Copied parts of these over to the V3.1.5 branch to complete migration. Thanks for your help.

**Pull request closed without merging**
